spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: 'jdbc:postgresql://localhost:5432/dev'
    username: postgres
    password: postgrespass
    driverClassName: org.postgresql.Driver

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            TRACE