spring:
  profiles:
    active: dev
  jackson:
    time-zone: 'Europe/Moscow'
    deserialization:
      fail-on-unknown-properties: true
    mapper:
      sort-properties-alphabetically: true
  flyway:
    clean-on-validation-error: true
    locations: >-
      classpath:db/migration/common,classpath:db/migration/${spring.profiles.active}
